import pandas as pd

print('-----------------------')
data = pd.read_csv("train.csv")

print(data.dtypes)
print("Men:")
input('PassengerId')
print(data[data['Sex'] == 'male']['PassengerId'].describe())
input('Survived')
print(data[data['Sex'] == 'male']['Survived'].describe())
input('Pclass')
print(data[data['Sex'] == 'male']['Pclass'].describe())
input('Age')
print(data[data['Sex'] == 'male']['Age'].describe())
input('SibSp')
print(data[data['Sex'] == 'male']['SibSp'].describe())
input('Parch')
print(data[data['Sex'] == 'male']['Parch'].describe())
input('Fare')
print(data[data['Sex'] == 'male']['Fare'].describe())
input()
print("--------------------------------------------------------")
print("Women:")
input('PassengerId')
print(data[data['Sex'] == 'female']['PassengerId'].describe())
input('Survived')
print(data[data['Sex'] == 'female']['Survived'].describe())
input('Pclass')
print(data[data['Sex'] == 'female']['Pclass'].describe())
input('Age')
print(data[data['Sex'] == 'female']['Age'].describe())
input('SibSp')
print(data[data['Sex'] == 'female']['SibSp'].describe())
input('Parch')
print(data[data['Sex'] == 'female']['Parch'].describe())
input('Fare')
print(data[data['Sex'] == 'female']['Fare'].describe())
input()
